### ISSUE TITLE
Authorizenet sdk conflicts with Magento v2.2.1 and up

### ISSUE THREAD

**Issue by pmclain** [pmclain/module-authorizenetcim#14]
The requirement for `symfony/yaml` conflicts with the versions of `symfony/dependency-injection` and `symfony/console`. I guess it's time to roll our own request adapters :(

**Comment by JstrzAtW2M** [comment]
The ever changing magento 2

**Comment by pmclain** [comment]
I've put together a bare-bones SDK for Authorize.net that I think will work, https://github.com/pmclain/authorizenet-php-sdk. Now I need to rework the module's Gateway and Adapter classes to use it.
