### ISSUE TITLE
The element 'paymentProfile' in namespace has incomplete content

### ISSUE THREAD

**Issue by JstrzAtW2M** [pmclain/module-authorizenetcim#19]
Customers started getting this error. Any ideas on what this might be
The element 'paymentProfile' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has incomplete content. List of possible elements expected: 'paymentProfileId' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'. [] []

**Comment by pmclain** [comment]
This is likely an issue with the replacement sdk. I've got a few questions to hopefully trace down the issue:

- Is it primarily happening to new or logged in users?
- If logged in users, are they using a new credit card or an existing saved card?

**Comment by JstrzAtW2M** [comment]
I sounds like new users work, but existing users do not

**Comment by pmclain** [comment]
Thanks. I'll take a look as soon as possible, though I'm on holiday for the next two weeks and have limited availability.

**Comment by pmclain** [comment]
Updating `pmclain/authorizenet-php-sdk` to v0.1.5 will fix this. I've updated the requirement in composer.json.
