### ISSUE TITLE
Class Pmclain\\Authnet\\MerchantAuthentication does not exist in magento 2.1.7

### ISSUE THREAD

**Issue by pinnacledeveloper123** [pmclain/module-authorizenetcim#20]
I get this error in magento 2.1.7. 

Class Pmclain\\Authnet\\MerchantAuthentication does not exist

I copied zip and moved data to Pmclain/AuthorizenetCim, 

Can I get this module in zip as i am getting errors in composer installation of this module in magento 2.1.7

**Comment by pinnacledeveloper123** [comment]
I am getting this error using composer 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pmclain/magento2-authorizenetcim v1.0.0 requires magento/framework ~101.0.0 -> satisfiable by magento/framework[101.0.0-rc21, 101.0.0-rc22, 101.0.0-rc23, 101.0.0-rc30, 101.0.0, 101.0.1, 101.0.2].
    - pmclain/magento2-authorizenetcim v1.0.1 requires magento/framework ~101.0.0 -> satisfiable by magento/framework[101.0.0-rc21, 101.0.0-rc22, 101.0.0-rc23, 101.0.0-rc30, 101.0.0, 101.0.1, 101.0.2].
    - magento/framework 101.0.0-rc21 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.0-rc22 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.0-rc23 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.0-rc30 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.0 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.1 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.2 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - Conclusion: don't install composer/composer 1.4.1
    - Installation request for pmclain/magento2-authorizenetcim ^1.0 -> satisfiable by pmclain/magento2-authorizenetcim[v1.0.0, v1.0.1].

**Comment by pmclain** [comment]
v1.x does not support Magento 2.1.x. Please refer to the compatibility table included in the readme.
