### ISSUE TITLE
Integrate authorizenetcim with your one-click-checkout module

### ISSUE THREAD

**Issue by pinnacledeveloper123** [pmclain/module-authorizenetcim#22]
I am on magento 2.1.7. I can't use magento instant purchase in 2.1.7. Both your autorizenetcim and one click checkout module are working fine. My question is I don't want to use braintree payment, I want to use authorizenetcim with one click checkout. How do i replace braintree with authorizenetcim for one click checkout.

**Comment by pmclain** [comment]
The one click checkout module is abandoned. If you are looking for a similar feature it would be best to upgrade magento to at least v2.2.2 to use instant purchase.
