### ISSUE TITLE
Uncaught ReferenceError: response is not defined

### ISSUE THREAD

**Issue by prestashoppay** [pmclain/module-authorizenetcim#3]
@pmclain ,

We have fresh magento 2.1 and installed authorized.netcim your module.
when we entered payment details click the place order button we are getting below error, in browser consloe and unable move to next step,.

Kindly let us know your suggestion to fix the issues.
Note : We are using authorized.net sandbox mode .

`pmclain_authorizenetcim.js:61 Uncaught ReferenceError: response is not defined
    at Object.<anonymous> (pmclain_authorizenetcim.js:61)
    at fire (jquery.js:3099)
    at Object.add [as fail] (jquery.js:3145)
    at UiClass.placeOrder (pmclain_authorizenetcim.js:57)
    at HTMLButtonElement.<anonymous> (/m2fresh/pub/static/version1505797097/frontend/Magento/luma/en_US/knockoutjs/knockout.js:3863)
    at HTMLButtonElement.dispatch (jquery.js:4624)
    at HTMLButtonElement.elemData.handle (jquery.js:4292)`

**Comment by prestashoppay** [comment]
We have updated in your code , when we entered payment details click the place order button we are getting below error, in browser consloe and unable move to next step,.

Kindly let us know your suggestion to fix the issues.

`{messages: {resultCode: "Error", message: [{code: "E00003", text: "Root element is missing."}]}}`
`message :
[{code: "E00007", text: "User authentication failed due to invalid authentication values."}]`

**Comment by pmclain** [comment]
Authorize.net is rejecting your tokenization request. You'll want to check that you have valid values in the admin configuration for `Client Key` and `API Login ID`.

**Comment by prestashoppay** [comment]
@pmclain, Thanks for your support.
As per your suggestions we have updated the proper `Client key` and `API login ID`. Now we are getting proper response from authorize.net sandbox and attached the screenshots and also some facing some issues after successfull response.

Request API : 
![error_cim](https://user-images.githubusercontent.com/27668186/30594827-0b1c5698-9d6d-11e7-8cf1-6f0b9dc01e5e.png)

Request API Success : 
![error_cim1](https://user-images.githubusercontent.com/27668186/30594853-1faca784-9d6d-11e7-8734-377388c33d04.png)

Payment Information 400 Error : 
![error_cim2](https://user-images.githubusercontent.com/27668186/30594940-5435cf76-9d6d-11e7-88f8-eb1e6fb3c0fb.png)

Error message log first line only : 
`{"message":"ReflectionException: Class net\\authorize\\api\\contract\\v1\\MerchantAuthenticationType does not exist in}`

Kindly check the attachement and error log and let you know your suggestions to fix the issues.

Thanks

**Comment by pmclain** [comment]
How did you install the module?

**Comment by prestashoppay** [comment]
@pmclain , Installed the authorize.net cim module using ssh cmd and also we are using the fresh magento pack 2.1.6.
kindly let us know your suggestion.

Thanks

**Comment by pmclain** [comment]
Did you run `composer require pmclain/magento2-authorizenetcim`? The error you are describing sounds like the Authorize.net SDK is not installed.

**Comment by prestashoppay** [comment]
@pmclain, we have downloaded the files from github and uploaded into magento 2 folder and run the below cmd in ssh.

`php bin/magento module:enable Pmclain_AuthorizenetCim`

Do you want us to do the installation via  `composer require` cmd ?
Thanks

**Comment by pmclain** [comment]
Installing the module manually means you need in add/confirm the dependencies outlined in `composer.json`.

**Comment by prestashoppay** [comment]
@pmclain ,
As per your suggestion we are trying to install the extension using composer and get back to you shortly.
Thanks ,

**Comment by prestashoppay** [comment]
@pmclain ,

Thank you for your suggestion , It's Working fine ..


Thanks,

**Comment by prestashoppay** [comment]
@pmclain ,

Is there any options refund option in your module.

**Comment by prestashoppay** [comment]
Hello @pmclain ,

Is there any updates ...

**Comment by pmclain** [comment]
The module works with Magento's native creditmemo process. I'm not sure I understand the issue.

**Comment by prestashoppay** [comment]
@pmclain , Thanks for your reply .

Is there any options for store card details page "EDIT" button on custome store card details.

**Comment by pmclain** [comment]
Additional information about order management and the card vault can be found in the Magento Open Source User Guide http://docs.magento.com/m2/ce/user_guide/getting-started.html

**Comment by prestashoppay** [comment]
@pmclain , Thanks for your reply .

**Comment by raviozainfo** [comment]
Hi prestashoppay & pmclain

How to resolve pmclain_authorizenetcim.js:61 Uncaught ReferenceError: response is not defined at Object.
 issue
Thanks
