### ISSUE TITLE
Must be an instance of net\authorize\api\contract\v1\ANetApiRequestType on 2.1.9

### ISSUE THREAD

**Issue by JstrzAtW2M** [pmclain/module-authorizenetcim#5]
I keep getting this error
Uncaught TypeError: Argument 1 passed to net\authorize\api\controller\CreateCustomerProfileController::__construct() must be an instance of net\authorize\api\contract\v1\ANetApiRequestType, instance of Magento\Framework\ObjectManager\ObjectManager given

It looks like it's happening in CreateCustomerProfileControllerFactory.php because you're using ObjectManager create on a non-magento component.
https://github.com/magento/magento2/issues/9760

Does this extension work with 2.1.*? I'm on 2.1.9

**Comment by pmclain** [comment]
Honestly, I did almost all of the development on 2.2-dev branch and made assumptions of compatibility based on the APIs of the core modules used by this module. I'll fire up a current 2.1.x instance shortly to confirm.

**Comment by pmclain** [comment]
Yup. Confirmed this does not work on v2.1.11. I'm going to try fixing the factory classes this weekend.
