### ISSUE TITLE
Uncaught ReferenceError: response is not defined in pmclain_authorizenetcim

### ISSUE THREAD

**Issue by raviozainfo** [pmclain/module-authorizenetcim#7]
Uncaught ReferenceError: response is not defined
    at Object.<anonymous> 
    at fire (jquery.js:3099)
    at Object.add [as fail] (jquery.js:3145)
    at UiClass.placeOrder 
    at HTMLButtonElement.<anonymous> (knockout.js:3863)
    at HTMLButtonElement.dispatch (jquery.js:4624)
    at HTMLButtonElement.elemData.handle (jquery.js:4292)

pmclain_authorizenetcim.js:61
line -- for (var i = 0; i < **response**.messages.message.length; i++) {

**Comment by pmclain** [comment]
The javascript is not properly handling an error from authorize.net. This seems to happen when Authorize.net is rejecting your tokenization request. You'll want to check that you have valid values in the admin configuration for Client Key and API Login ID.

I'll get a patch out shortly to properly handle the error responses from tokenization requests.

**Comment by raviozainfo** [comment]
Hi, pmclain. 
Thanks for reply now response is valid.
Is there any way to bypass https required in localhost.(using code)
i am getting E_WC_02: A HTTPS connection is required. error.
